import XCTest
import GRDB
@testable import Chronicle

/// Validates the v9 multi-provider migration:
///  - Adds a `provider` column to every metadata table
///  - Defaults existing rows to `'claude'` so v0.1.x data carries forward
///  - Adds composite (provider, session_id) indexes for query perf
///  - Is idempotent (re-running the full migration chain is a no-op)
final class MultiProviderMigrationTests: XCTestCase {

    // MARK: - Column shape

    func test_v9_addsProviderColumnToEveryMetadataTable() throws {
        let dbq = try DatabaseQueue()
        try Migrations.all(dbq)

        let expectedTables = [
            "sessions_index", "session_flags", "workspaces",
            "user_metadata", "smart_folders", "tags", "session_tags",
        ]
        try dbq.read { db in
            for table in expectedTables {
                let cols = try Row.fetchAll(db, sql: "PRAGMA table_info(\(table))")
                    .compactMap { $0["name"] as String? }
                XCTAssertTrue(
                    cols.contains("provider"),
                    "Table \(table) is missing the `provider` column after v9"
                )
            }
        }
    }

    // MARK: - Default value

    func test_v9_existingRowsDefaultToClaude() throws {
        let dbq = try DatabaseQueue()

        // 1. Build a v8-shaped DB (everything before v9).
        try Migrations.v1(dbq)
        try Migrations.v2(dbq)
        try Migrations.v3(dbq)
        try Migrations.v4(dbq)
        try Migrations.v5(dbq)
        try Migrations.v6(dbq)
        try Migrations.v7(dbq)
        try Migrations.v8(dbq)

        // 2. Seed pre-multi-provider rows in every metadata table. None of
        //    these inserts mention `provider` — they're shaped exactly like
        //    a v0.1.x bootstrap would write.
        try dbq.write { db in
            try db.execute(sql: """
                INSERT INTO workspaces
                    (id, decoded_path, "group", display_name, indexed_at, cwd, git_branch, claude_version)
                VALUES ('ws-A', '/Users/x/A', 'group-A', 'A', '2024-01-01', '/Users/x/A', 'main', '1.0.0')
                """)
            try db.execute(sql: """
                INSERT INTO sessions_index
                    (session_id, workspace_id, title, created_at, last_modified_at,
                     message_count, token_count, file_size_bytes, file_mtime,
                     total_input_tokens, total_output_tokens, model)
                VALUES ('00000000-0000-4000-8000-000000000001', 'ws-A', 'pre-v9',
                        '2024-01-01', '2024-01-01', 5, 100, 1024, 1700000000.0,
                        50, 50, 'claude-sonnet-4')
                """)
            try db.execute(sql: """
                INSERT INTO session_flags (session_id, flag_name)
                VALUES ('00000000-0000-4000-8000-000000000001', 'git_push')
                """)
            try db.execute(sql: """
                INSERT INTO user_metadata
                    (session_id, is_pinned, is_archived, is_deleted,
                     deleted_at, custom_title, note, updated_at)
                VALUES ('00000000-0000-4000-8000-000000000001', 1, 0, 0, NULL, NULL, NULL, 1700000000)
                """)
            try db.execute(sql: """
                INSERT INTO smart_folders (name, query_json, sort_order, is_builtin)
                VALUES ('Pinned', '{}', 0, 1)
                """)
            try db.execute(sql: """
                INSERT INTO tags (name, color_hue) VALUES ('legacy-tag', 30)
                """)
            // tag id is autogenerated; reference it via a SELECT so the test
            // doesn't depend on AUTOINCREMENT internals.
            let tagID: Int64 = try Int64.fetchOne(
                db, sql: "SELECT id FROM tags WHERE name = 'legacy-tag'") ?? -1
            try db.execute(sql: """
                INSERT INTO session_tags (session_id, tag_id)
                VALUES ('00000000-0000-4000-8000-000000000001', ?)
                """, arguments: [tagID])
        }

        // 3. Run the v9 migration on this populated DB.
        try Migrations.v9(dbq)

        // 4. Every existing row must have provider='claude'.
        try dbq.read { db in
            for table in ["workspaces", "sessions_index", "session_flags",
                          "user_metadata", "smart_folders", "tags", "session_tags"] {
                let claudeRows = try Int.fetchOne(
                    db, sql: "SELECT COUNT(*) FROM \(table) WHERE provider = 'claude'") ?? -1
                let totalRows = try Int.fetchOne(
                    db, sql: "SELECT COUNT(*) FROM \(table)") ?? -1
                XCTAssertGreaterThan(totalRows, 0, "Test seeded zero rows in \(table)?")
                XCTAssertEqual(
                    claudeRows, totalRows,
                    "All pre-v9 rows in \(table) must default to provider='claude'"
                )
            }
        }
    }

    // MARK: - Composite indexes

    func test_v9_compositeIndexesExist() throws {
        let dbq = try DatabaseQueue()
        try Migrations.all(dbq)

        let expectedIndexes = [
            "sessions_index_pk",
            "user_metadata_pk",
            "session_flags_pk",
            "session_tags_pk",
            "workspaces_provider_idx",
            "smart_folders_provider_idx",
        ]
        try dbq.read { db in
            for idx in expectedIndexes {
                let exists = try Bool.fetchOne(
                    db,
                    sql: "SELECT 1 FROM sqlite_master WHERE type='index' AND name=?",
                    arguments: [idx]
                ) ?? false
                XCTAssertTrue(exists, "Index \(idx) missing after v9")
            }
        }
    }

    // MARK: - Idempotency

    func test_v9_isIdempotent() throws {
        let dbq = try DatabaseQueue()
        try Migrations.all(dbq)
        try Migrations.v9(dbq)
        try Migrations.v9(dbq) // must not throw

        // Confirm shape unchanged: still exactly one `provider` column.
        try dbq.read { db in
            let cols = try Row.fetchAll(db, sql: "PRAGMA table_info(sessions_index)")
                .compactMap { $0["name"] as String? }
            let providerCols = cols.filter { $0 == "provider" }
            XCTAssertEqual(providerCols.count, 1)
        }
    }

    func test_allMigrationsRunTwice_isNoOp() throws {
        let dbq = try DatabaseQueue()
        try Migrations.all(dbq)
        try Migrations.all(dbq)
    }

    // MARK: - Provider value persists

    func test_v9_providerColumnAcceptsCodexAndGeminiValues() throws {
        let dbq = try DatabaseQueue()
        try Migrations.all(dbq)

        // Three workspaces, one per provider — confirms the column is text
        // and unconstrained beyond the schema's NOT NULL DEFAULT 'claude'.
        try dbq.write { db in
            try db.execute(sql: """
                INSERT INTO workspaces
                    (id, decoded_path, "group", display_name, indexed_at, provider)
                VALUES ('ws-claude', '/c', 'g', 'C', '2026-04-26', 'claude'),
                       ('ws-codex',  '/x', 'g', 'X', '2026-04-26', 'codex'),
                       ('ws-gemini', '/i', 'g', 'I', '2026-04-26', 'gemini')
                """)
        }
        try dbq.read { db in
            let providers = try String.fetchAll(
                db, sql: "SELECT provider FROM workspaces ORDER BY id")
            XCTAssertEqual(providers, ["ws-claude", "ws-codex", "ws-gemini"]
                .map { id in
                    switch id {
                    case "ws-claude": return "claude"
                    case "ws-codex":  return "codex"
                    default:          return "gemini"
                    }
                })
        }
    }
}
